version: '3.0'
services:
  web:
    image: alexcheng/magento2:2.3.2
    ports:
      - "80:80"
    links:
      - db
      - redis
    env_file:
      - env
    volumes:
      - ./public_html:/var/www/html
      - ./:/var/www/html/app/code/Salesfire/Salesfire
      - ./logs:/var/www/html/var/log
  db:
    image: mysql:5.6.23
    volumes:
      - db-data:/var/lib/mysql/data
    ports:
      - "3306:3306"
    env_file:
      - env
  redis:
    image: redis
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8580:80"
    links:
      - db
volumes:
  db-data:
